Add support for Paddles new Sandbox environment
paddle-python/paddle-client pull request #4
Opened 2021-02-26 17:10 UTC by Wolf-Byte

With the release of Paddles much awaited sandbox environment I have updated the package to add sandbox support.

- When initialising PaddleClient you can now pass the parameter 'sandbox' (default=None)
- If the parameter is not set (equals None) the sandbox variable is loaded from the new environment variable 'PADDLE_SANDBOX'. The variable must equal "True" to enable sandbox via the environment variable.

All tests have been updated to support the sandbox environment.

I found several issues with the tests so I included my fixes in the PR. Hopefully this will help any future contributors.

Notes:
- The last commit (cba3b5f961c2f60e750748ea5deadc5f4b19e364) includes the feature request and all prior commits include the test fixes.
- All tests where run agains the sandbox environment which paddle state is identical to the production environment. If you could please run the tests on your production environment that would be great. Unfortunately I am unable to do this on our production environment. I have, however, contacted Paddle to request a new live account so I can run live tests in the future.

Read more about the sandbox environment here:
[https://developer.paddle.com/getting-started/sandbox](https://developer.paddle.com/getting-started/sandbox)

Tests passed
68 passed, 4 skipped, 1 xpassed, 2 warnings in 53.15s

2021-03-15 20:49 UTC, pyepye commented
Hi @Wolf-Byte 

Sorry about the lack of reply, I had totally missed the GitHub notification. 

I had also missed the fact Paddle had released a sandbox environment, that is great news.

Please give me a day or 2 to review the code and re-setup my production environment to ensure the tests run.

Thank you for for the PR and your hard work.

2021-03-20 02:10 UTC, pyepye requested changes
Thanks for all the work so far. I've requested a few changes based on me running the tests against my production environment.  
Hopefully the changes requested mean the tests pass for you as well. The problem is the test setup is a pain making the tests a little flakey.

With that in mind...

Looking at how the Paddle sandbox environment works it looks like the best approach for the long term will be to update the tests to use the sandbox environment instead of requiring / assuming the person testing this package has set up their prod environment correctly (which is a pain right now).

I think the current plan should be to make the tests only run against the sandbox environment:

1. Create a sandbox account for this package
1. Add fixtures to create plans and subscriptions etc - basically remove the need for the environmental variables like `PADDLE_TEST_DEFAULT_SUBSCRIPTION_ID`. They should be idempotent and only create new things if old ones have been deleted for whatever reason
1. Create some manual payments, subscriptions and one-off purchases that can be used in the future
1. Remove the mock tests and make the none mock / skipped tests the default and run all the time
1. Update the docs on how to easily make new payments, subscriptions and one-off purchases based on the plans and subscriptions created by the tests if the correct data does not exist

I understand the above is quite a bit of work and don't expect you to do it, I'm more stating my current intention / next steps to  remove some of issues with making the tests run and pass for everyone that tries.

As I have requested some changes to this pull request but with the above in mind I will also be working on the tests and the code you have written, I wanted to give you a choice on next steps for this pull request on beyond:

1. Leave everything how it is now with a big thanks from me. I'll fix up this pull request while I implement the above
2. You can fix up the comments, we can get this PR merged for now and I'll make the changes above in my own time
3. You can help with the above as well - this really isn't expected I just wanted to give you the option incase you are interested

Please let me know which one you would like to do. And again thank you very much for everything so far. Hopefully it's clear that I appreciate the effort and there is no pressure for you to continue you current contribution if you don't want to.

2021-03-26 01:28 UTC, merged

2021-03-26 01:34 UTC, pyepye commented
Hi @Wolf-Byte 

I've had a few hours spare over the last week so I decided to take a run at the above. 

Your changes in this pull request have now been merged into master via another pull request with some additional changes = https://github.com/paddle-python/paddle-client/pull/6

We now only have 1 test which requires any kind of mocking and more importantly we have been able to really simplify the test setup for this package which is fantastic.

Thanks again for your help.

2021-03-27 15:19 UTC, Wolf-Byte commented
@pyepye Sorry for the delay in getting back to you surrounding the PR, we have had a product launch and I fell behind on my GitHub notifications.

Thank you for soldiering on with the changes and releasing an update to Pypi. I will take a proper look over your notes and adjustments in the week.

2021-03-31 14:05 UTC, pyepye commented
@Wolf-Byte No worries at all. I just had some free time so decided to plow on with the changes. 

If you have any question just let me know on here.

And I hope the product launch went well.